### ISSUE TITLE
extension install impossible

### ISSUE THREAD

**Issue by pokyto** [rxu/thanks_for_posts#118]
Hi!

the extension does not appear in the list of extensions to install

I did as usual to install an extension but nothing appears

I tried with the master branch and 3.2 but same result

using phpbb [3.3.11] with phph 8.2.0 and Flat-style

any idea ??

regards

**Comment by Hareon** [comment]
Same here. I installed on /ext/rxu/thanksforposts

phpBB 3.3.11 with php 7.4

**Comment by rxu** [comment]
It should be `ext/gfksx/thanksforposts`.

**Comment by Hareon** [comment]
Thank you for reply and now I could find it in the menu, but when I active, I have another problem.
![image](https://github.com/rxu/thanks_for_posts/assets/54816136/0eeca602-5301-431d-9e9d-74a611e8309d)

"Something went wrong while executing the request and an exception was created. Changes made before the error occurred have been rolled back as best as possible. However, you should check the forum for errors.

Unexpectedly the "thanks_reput_image" configuration option does not exist."

I don't know if this has relation with the problem I had with another plugin of the type I tried to activate today, but the other version has a problem (which I don't know how to resolve yet) in the database. https://www.phpbb.com/community/viewtopic.php?p=15990268#p15990268

Does this extension have any conflict with the other extension in this topic?

I want to try to clear the another to activate, but I don't know how because I deleted (some times) the db_ext>naguissa/thanksforposts but I dont know why, something dont be deleted.

**Comment by Hareon** [comment]
Update: Something in your version helped delete the other's data.

There was an error to activate. So I went back to phpmyadmin and deleted (again) the table ext (ext_name, ext_active, ext_state) VALUES ('naguissa/thanksforposts', 0, 's:13:\"notifications\";')

So your version of thanksforposts gave you the option to "delete data". I even tried to activate again without deleting, but it gave the same error as the print I sent in the comment above.

Then I went to delete data and it was deleted successfully.

Then I tried to activate your version of the extension and it activated!

**Comment by rxu** [comment]
> Does this extension have any conflict with the other extension in this topic?

I have no idea honestly. But as far as that one is a fork of this one I suppose they can't live side by side so you have to purge one to install another and vise versa.

**Comment by Hareon** [comment]
I believe that since the base of both extensions was the same, one may be able to clean the other. When deleting data from this version, it ended up also deleting something that the other version was unable to delete, and this made activation possible. In the other version it only had Error 500.

**Comment by rxu** [comment]
> one may be able to clean the other

Probably, but only partially, as namespaces are different. So you can get a mess of files and data as a result.

**Comment by Hareon** [comment]
For me this problem is solved. Thank you very much. I'll report it on that topic to try to help anyone that have the same problem.

Oh, how am I going to use it, I saw that the translation into Portuguese is very poor. When I do the translation, I will send it here to you.

**Comment by pokyto** [comment]
> thanksforposts

oki i changed the ext's path by the one you provided but same result the extension doesn't appears in the non installed ext and can't be activated 

weird !!!
